---
# tasks file for nftables
- name: include os-specific variables
  include_vars: "{{ansible_os_family}}.yml"

# - include_tasks: setup-redhat.yml
#   when: ansible_os_family == "RedHat"

- include_tasks: setup-debian.yml
  when: ansible_os_family == "Debian"
